# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    disable_automatic_code_signing(
      path: "FastTest.xcodeproj", 
      code_sign_identity:"iPhone Distribution",
      profile_uuid:"ef19e3f9-e817-4da6-84ac-d79e515ebb87",
      team_id:"Q7UDHAD55J"
    )

    build_app(scheme: "FastTest")

    enable_automatic_code_signing(
      path: "FastTest.xcodeproj", 
      team_id:"Q7UDHAD55J"
    )
    pilot
  end
end
